### ISSUE TITLE
悬浮菜单收起的时候，悬浮球左边的区域被弹出菜单所遮挡，无法接受点击事件

### ISSUE THREAD

**Issue by mahaiming0611** [huxq17/FloatBall#2]

**Comment by huxq17** [comment]
这问题我很早就发现了，所以没有去推广项目，解决办法是用两个view把悬浮球和展开的菜单分开。在菜单收起的时候把菜单的view remove掉就可以了，或者你不需要菜单的话不添加菜单也不会有这个问题。

**Comment by oksimple** [comment]
如何解决小米手机默认 关闭权限的问题？

**Comment by huxq17** [comment]
什么版本的手机

**Comment by huxq17** [comment]
现在的已经没有这个问题了。
