### ISSUE TITLE
怎么让子菜单默认展开

### ISSUE THREAD

**Issue by GeniusJerry** [huxq17/FloatBall#20]
怎么让子菜单默认展开

**Comment by huxq17** [comment]
试试FloatBallManager#onFloatBallClick()

**Comment by GeniusJerry** [comment]
您好，试过了，这样的话，子菜单会在屏幕左上角展开，但是我的按钮是设置在右边居中

**Comment by huxq17** [comment]
我刚更新了，现在能默认展开菜单，ni看看

**Comment by GeniusJerry** [comment]
好的，我试试谢谢

**Comment by GeniusJerry** [comment]
您好，可以展开了，您不能不帮忙再调一下主按钮和子菜单之间的间隔？调大一点，现在感觉距离有点短，不美观

**Comment by huxq17** [comment]
com.huxq17.floatball.libarary.menu.MenuLayout里有个MIN_RADIUS，现在在构造函数里给的值是65dp，你把它给大点距离就长了，如果改了以后菜单不能完全显示，再把FloatMenuCfg#mSize给大点。

**Comment by GeniusJerry** [comment]
好的，非常感谢
