### ISSUE TITLE
为什么要做成打开就执行一次点击事件呢？

### ISSUE THREAD

**Issue by tiankaitiankai** [huxq17/FloatBall#21]
每次一打开什么都不做就点击一次悬浮球

**Comment by huxq17** [comment]
这会有什么问题么？

**Comment by tiankaitiankai** [comment]
没问题，因为要为APP做个悬浮球，是用户有需要时才会点击触发，看了您的代码最后才发现是一打开就执行了一次点击事件，所以才有这个疑问，现在自己重新写了一个😁
