### ISSUE TITLE
点击悬浮的事件 露出来了吗？

### ISSUE THREAD

**Issue by oksimple** [huxq17/FloatBall#3]
我现在想要 点击悬浮有其他事件，不想要menu 怎么弄呢

**Comment by huxq17** [comment]
mFloatBall = new FloatBall.Builder(getApplicationContext()).icon(singleIcon).build();
这样，不要传menu就可以了。

**Comment by oksimple** [comment]
我自己在 showMenu() 里面添加了一个 回调

**Comment by huxq17** [comment]
加上去了，直接调用floatball.setOnClickListener就可以，MainActivity里有。

**Comment by oksimple** [comment]
666
