### ISSUE TITLE
请问,是不是只有Build.VERSION.SDK_INT>=23才能使用悬浮球

### ISSUE THREAD

**Issue by sweet2o09** [huxq17/FloatBall#5]
请问,是不是只有Build.VERSION.SDK_INT>=23才能使用悬浮球

**Comment by sweet2o09** [comment]
如果只是做应用内的悬浮球,是不是就不需要权限了?

**Comment by huxq17** [comment]
api14以上都能用，应用内的也需要权限。

**Comment by sweet2o09** [comment]
我是华为3.1的系统,提示没开启权限,但是跳转到通知那边后不知道在哪里开启
最后我只能修改代码,默认权限查询返回true,悬浮球就出来了,你知道悬浮球权限都是在哪里设置的么?
@huxq17

**Comment by huxq17** [comment]
你仔细看看readme，有写的。
