### ISSUE TITLE
您好,miui9小米5s上跑demo不显示悬浮窗

### ISSUE THREAD

**Issue by fy5220** [huxq17/FloatBall#6]
您好,我在miui9小米5s上跑demo,不显示悬浮窗,权限已开启.没有改任何代码.有空可以帮看下么!

**Comment by huxq17** [comment]
权限给了？

**Comment by fy5220** [comment]
给了..手动打开给设置的权限.

**Comment by fy5220** [comment]
还有一个问题在8.0模拟器上跑demo,点击悬浮球展开menu,然后再点收回的时候,会有个黑框显示一下.目前手上没有8.0的真机.所以不知道是不是模拟器问题.但是其他版本模拟器没有这个现象.

**Comment by huxq17** [comment]
应该是模拟器的问题，关于小米5s的哪个问题，你看看hasFloatBallPermission里返回的值是什么

**Comment by fy5220** [comment]
手动去设置授予权限后,返回app里,hasFloatBallPermission返回true

**Comment by huxq17** [comment]
能给一个可运行的demo么？

**Comment by fy5220** [comment]
额..就是下的你的demo.没有改任何东西.直接跑的

**Comment by huxq17** [comment]
没有miui9的机子，在miui8.0上是正常。

**Comment by fy5220** [comment]
在等等看其他人有没有这问题吧..我只有一个miui的小米5s..但是其他手机vivo 华为 oppo啥的都没问题..就只有这个小米有问题.好奇葩.

**Comment by YLAndsoft** [comment]
你好，悬浮球第一次显示的位置可以手动改变吗？我测试demo好像是固定了。

**Comment by huxq17** [comment]
什么情况了，还有问题么？我在miui9的机器上没发现问题。

**Comment by fy5220** [comment]
- -我的还是一样的问题..小米5s miui9开发版 8.1.11.直接clone代码运行.然后给予弹窗权限.还是不显示...

**Comment by gitzsl** [comment]
你好，大神，我在小米5上跑demo，同样显示不了悬浮窗，确认权限给了

**Comment by huxq17** [comment]
终于有miui9的手机了，已经解决。

**Comment by stven0king** [comment]
@huxq17 请问你是怎么解决的？直接使用原生的吐司么？

**Comment by huxq17** [comment]
是改了下layoutparams的type,用的是TYPE_PHONE;
