### ISSUE TITLE
悬浮球第一次显示的位置可以手动改变吗？

### ISSUE THREAD

**Issue by YLAndsoft** [huxq17/FloatBall#8]

**Comment by huxq17** [comment]
FloatBallCfg ballCfg = new FloatBallCfg(ballSize, ballIcon);
        //可以设置悬浮球的初始位置是否在左边
        ballCfg.setLeft(false);
        //设置悬浮球初始位置y坐标偏移量，屏幕左上角是原点
        ballCfg.setOffsetY(200);
最新的代码提供了上述的方式来设置第一次显示的位置。

**Comment by huxq17** [comment]
补一句，如果不调用setOffsetY方法的话，默认在竖直方向上是居中的。

**Comment by YLAndsoft** [comment]
感谢！
